### ISSUE TITLE
Significant offset on attachment

### ISSUE THREAD

**Issue by pt1243** [KSP-RO/ROSolar#7]
As shown in the screenshots below, there's quite a large gap between where the solar panel is attached and where it initially is placed. As far as I can tell, there is no impact on functionality. Tested with a clean install of 1.8.1 with RO and all dependencies.
![screenshot1](https://user-images.githubusercontent.com/64465231/80466890-4e81fd00-8967-11ea-8442-94f1b4014bc1.png)
![screenshot2](https://user-images.githubusercontent.com/64465231/80466895-50e45700-8967-11ea-84ee-b3b9fa75e06f.png)
![screenshot3](https://user-images.githubusercontent.com/64465231/80466900-517ced80-8967-11ea-8c61-06f63e22b448.png)

Apologies if this is a simple or quick fix I should do myself - I had a look in the config files but didn't see anything unusual.

**Comment by DRVeyl** [comment]
I've been working on this recently.  Will get patched in a release soon.

If you installed from master, try just getting the release or install through CKAN.  The master branch as of right now is out-of-sync with the ROLib release, so that over-large offset might be a result of changes there.  Also try clicking the "Reset model" button twice in the panel's PAW.

**Comment by DRVeyl** [comment]
Should now be fixed with https://github.com/KSP-RO/ROSolar/releases/tag/v1.1 and https://github.com/KSP-RO/ROLibrary/releases/tag/v1.1  (both are needed together)

**Comment by pt1243** [comment]
Great - I will give this a try soon and see if it fixes the issue.

**Comment by pt1243** [comment]
They're working perfectly now - thanks!
